<?php

namespace app\models;

use Yii;
use yii\web\IdentityInterface;
use app\models\Position;
use app\models\Part;

/**
 * This is the model class for table "User".
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $address
 * @property string $password
 * @property integer $role_id
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    public function beforeSave($insert)
    {
        if(parent::beforeSave($insert))
        {
            if($this->isNewRecord)
            {
                $this->password = \Yii::$app->security->generatePasswordHash($this->password);
            }
            return true;
        }
        return false;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'User';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'email', 'phone', 'address', 'password', 'role_id'], 'required'],
            [['role_id'], 'integer'],
            [['name', 'email', 'phone', 'address', 'password'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'email' => 'Email',
            'phone' => 'Телефон',
            'address' => 'Адресс',
            'password' => 'Пароль',
            'role_id' => 'Уровень пользователя',
        ];
    }

    public function getVolParts()
    {
        return $this->hasMany(Part::className(), ['vol_id' => 'id']);
    }

    public function getRestPositions()
    {
        return $this->hasMany(Position::className(), ['restraunt_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(get_called_class());
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
//        return static::findOne(['access_token' => $token]);
    }

    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return null;
    }

    public function validatePassword($password)
    {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }

    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;


    }

    public function save($runValidation = true, $attributeNames = null)
    {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}
